name: Verify page title idea
on:
  push:
    branches: [ master ]
    paths:
      - "idea/easyMode/lang/**"
  pull_request:
    branches: [ master ]
    paths:
      - "idea/easyMode/lang/**"

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0

      - name: Verify page title
        run: |
          cd .github/workflows/wikiLinkExist
          deno run --allow-net --allow-read src/main.ts ../../../idea/easyMode/lang
